clean:
	rm -rf __pycache__/ solution.pl prolog_result.txt *.out *put.txt

sudoku:
	python validator.py --stdio zad5 python sudoku.py

ex1:
	python validator.py zad1 python3 ex1.py

ex2:
	python validator.py zad2 python3 ex2.py

test:
	python3 -m doctest ex1.py
