clean:
	rm -rf __pycache__/ prolog_result.txt *.out *put.txt *.pl

sudoku:
	python validator.py --stdio zad5 python sudoku.py

ex1:
	python validator.py zad1 python3 ex1.py

ex2:
	python validator.py zad2 python3 ex2.py

ex6:
	python validator.py zad6 python3 ex6.py

test:
	python3 -m doctest ex1.py
