clean:
	rm -rf __pycache__/
	rm *put.txt

ex1:
	python3 -m doctest ex1.py
	python validator.py zad1 python3 ex1.py	

ex2:
	python validator.py zad2 python3 ex2.py

ex4:
	python validator.py zad4 python3 ex4.py

ex5:
	python validator.py zad5 python3 ex5.py